### ISSUE TITLE
Cannot convert float NaN to integer

### ISSUE THREAD

**Issue by N-Bogdanovic-85** [DiamondLightSource/python-icebreaker#10]
Hi I run the test jobs  to "flatten" and to "group" micrographs through relion. These jobs completed successfully. Now, I selected my particles in relion and I am trying to assign ice thickness coeficient. I use the ib_group.py, input mics from grouped_micrographs.star and selected particles.star   without any parameter settings and single-threaded.

The job throws this error:

Traceback (most recent call last):
  File "python-icebreaker-master/src/icebreaker/cli/ib_group.py", line 79, in <module>
    main()
  File "python-icebreaker-master/src/icebreaker/cli/ib_group.py", line 70, in main
    run_job(project_dir, job_dir, other_args)
  File "python-icebreaker-master/src/icebreaker/cli/ib_group.py", line 34, in run_job
    ib_igroups.main

  File "/home/exx/Application/anaconda3/lib/python3.8/site-packages/icebreaker_em-0.3.5-py3.8.egg/icebreaker/ice_groups.py", line 65, in main
    ice_groups.append(int(micro_now[y1][x1] * 10000))
ValueError: cannot convert float NaN to integer

What could be the reason? I tried converting group_micrographs.star file using relion_convert_star to match the format of the native particle.star. Files I used by default are attached.

Could you please take a lot, as I would really like to test the capacity of the IceBreaker.

Thank you
[icebreaker_ptcl-proc-inputs.zip](https://github.com/DiamondLightSource/python-icebreaker/files/8672898/icebreaker_ptcl-proc-inputs.zip)

**Comment by samuelhaysom** [comment]
Hi @N-Bogdanovic-85,

I don't know precisely why the error occurs but if you make the following code alteration then it should allow ib_group to run without crashing.

In `ice_groups.py`:

alter the for loop on line 64-67 from:

```python
    if micro_now is not None:
        ice_groups.append(int(micro_now[y1][x1] * 10000))
    else:
        ice_groups.append(-1)
```

to:

```python
    try:
        ice_groups.append(int(micro_now[y1][x1] * 10000))
    except ValueError:
        print(f"warning, unable to append thickness value for particle at
        {x1= }, {y1= } in micrograph {mic}")
        print(f"assigning -1 as icethickness value for this particle")
        ice_groups.append(-1)
```
